# Generated by Django 5.2.8 on 2025-11-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название Бренда')),
            ],
            options={
                'verbose_name': 'Бранд',
                'verbose_name_plural': 'Бранды',
            },
        ),
    ]
